-- Caelus Cloud - Disable Row Level Security (RLS) on all public tables

ALTER TABLE IF EXISTS audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS servers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS credentials DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS providers DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS organization_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS organizations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS schema_migrations DISABLE ROW LEVEL SECURITY;
